let honorData=null,honorGrade=null;
async function honorFn(){const{data,error}=await sb.functions.invoke('student-honor-board',{body:{action:'summary'}});if(error)throw new Error(error.message||'تعذر تحميل لوحة الشرف');if(data?.error)throw new Error(data.message||data.error);return data}
function honorPct(v){return v==null?'—':Number(v).toFixed(Number(v)%1?1:0)+'%'}
function honorInitials(name){const p=String(name||'طالب').trim().split(/\s+/).filter(Boolean);return ((p[0]?.[0]||'ط')+(p[1]?.[0]||'')).toUpperCase()}
function honorBadges(list){return (list||[]).map(x=>`<span class="honorBadge">${esc(x)}</span>`).join('')}
function honorPodiumCard(s,rank){if(!s)return '<div></div>';const medal=rank===1?'🥇':rank===2?'🥈':'🥉';return `<div class="podiumCard rank${rank}"><div class="podiumMedal">${medal}</div><div class="podiumAvatar">${esc(honorInitials(s.full_name))}</div><div class="podiumName">${esc(s.full_name)}</div><div class="podiumGroup">${esc(s.group_code||'')}</div><div class="podiumScore">${honorPct(s.overall)} <small>مؤشر التميز</small></div><div class="podiumBadges">${honorBadges(s.badges)}</div></div>`}
function honorMetricCell(label,value){return `<div class="honorCellMetric"><b>${honorPct(value)}</b><span>${label}</span></div>`}
function honorTopRows(rows){if(!(rows||[]).length)return '<div class="honorEmpty">لا توجد بيانات كافية للترتيب حتى الآن.</div>';return `<div class="honorTopRow honorTopHead"><div>المركز</div><div>الطالب</div><div>التميز</div><div>اختبارات</div><div>التزام</div><div>واجب</div><div>منصة</div></div>`+rows.map(s=>`<div class="honorTopRow"><div><div class="honorRankNum">${s.rank}</div></div><div><div class="honorStudentName">${esc(s.full_name)}</div><div class="honorStudentMeta">${esc(s.group_code||'')} · ${honorBadges(s.badges)}</div></div><div class="honorOverallCell"><b>${honorPct(s.overall)}</b><div class="honorOverallBar"><i style="width:${Math.max(0,Math.min(100,Number(s.overall||0)))}%"></i></div></div>${honorMetricCell('اختبار',s.test_score)}${honorMetricCell('التزام',s.commitment_score)}${honorMetricCell('واجب',s.homework_score)}${honorMetricCell('منصة',s.platform_score)}</div>`).join('')}
function honorRiserCards(rows){if(!(rows||[]).length)return '<div class="honorEmpty" style="grid-column:1/-1">نحتاج نتيجتين على الأقل لكل طالب حتى يظهر نجوم الصعود.</div>';return rows.map(s=>`<div class="honorRiser"><div class="arrow">↗️</div><div class="rise">+${Number(s.improvement).toFixed(Number(s.improvement)%1?1:0)}</div><div class="nm">${esc(s.full_name)}</div><span class="meta">${esc(s.group_code||'')} · ${honorPct(s.previous_test)} ← ${honorPct(s.latest_test)}</span></div>`).join('')}
function honorLeaderRows(rows,field){if(!(rows||[]).length)return '<div class="honorEmpty">لا توجد بيانات بعد.</div>';return rows.map((s,i)=>`<div class="honorLeaderRow"><div class="honorLeaderNo">${i+1}</div><div><div class="honorLeaderName">${esc(s.full_name)}</div><div class="honorLeaderGroup">${esc(s.group_code||'')}</div></div><div class="honorLeaderValue">${honorPct(s[field])}</div></div>`).join('')}
function honorCategories(g){const c=[['🧪','فرسان الاختبارات','tests','test_score'],['🎯','أبطال الالتزام','commitment','commitment_score'],['📚','أبطال الواجب','homework','homework_score'],['🚀','نجوم المنصة','platform','platform_score']];return c.map(([icon,title,key,field])=>`<div class="honorCategory"><div class="honorCategoryTitle"><div class="honorCategoryIcon">${icon}</div><h4>${title}</h4></div>${honorLeaderRows(g.leaders?.[key]||[],field)}</div>`).join('')}
function honorGroupCard(g,i){if(!g)return '';return `<div class="honorGroupCard ${i===0?'leading':''}">${i===0?'<div>👑</div>':''}<div class="honorGroupCode">${esc(g.group_code||'')}</div><div class="honorGroupAvg">${honorPct(g.average)} <small>متوسط التميز</small></div><div class="small muted">${Number(g.eligible_count||0)} مؤهل من ${Number(g.total_count||0)} طالب</div>${g.leader?`<div class="small" style="margin-top:8px">متصدر المجموعة: <b>${esc(g.leader.full_name)}</b> · ${honorPct(g.leader.overall)}</div>`:''}</div>`}
function honorGroupsView(groups){const a=groups?.[0],b=groups?.[1];if(!a)return '<div class="honorEmpty" style="grid-column:1/-1">لا توجد بيانات مجموعات كافية.</div>';if(!b)return honorGroupCard(a,0);return `${honorGroupCard(a,0)}<div class="honorVs">VS</div>${honorGroupCard(b,1)}`}
function honorPersonalView(p,ownGrade){if(!ownGrade)return '<div class="honorPersonal"><div class="honorRankOrb"><div><b>↔</b><span>صف آخر</span></div></div><div><h3>أنت تشاهد منافسة الصف الآخر</h3><p>يمكنك استكشاف اللوحة، لكن مركزك الشخصي يظهر فقط داخل صفك الدراسي.</p></div></div>';if(!p)return '';if(!p.eligible)return `<div class="honorPersonal"><div class="honorRankOrb"><div><b>—</b><span>مركزك</span></div></div><div><h3>مكانك في السباق</h3><p>${esc(p.message||'بانتظار اكتمال البيانات.')}</p><div class="honorPersonalMetrics"><div class="honorMiniMetric"><span>البيانات الناقصة</span><b>${esc((p.missing||[]).join(' + ')||'—')}</b></div><div class="honorMiniMetric"><span>اختبارات</span><b>${honorPct(p.test_score)}</b></div><div class="honorMiniMetric"><span>التزام</span><b>${honorPct(p.commitment_score)}</b></div><div class="honorMiniMetric"><span>المنصة</span><b>${honorPct(p.platform_score)}</b></div></div></div></div>`;return `<div class="honorPersonal"><div class="honorRankOrb"><div><b>#${p.rank}</b><span>من ${p.total_eligible}</span></div></div><div><h3>🔥 مكانك في السباق</h3><p>${esc(p.message||'')}</p><div class="podiumBadges" style="justify-content:flex-start">${honorBadges(p.badges)}</div><div class="honorPersonalMetrics"><div class="honorMiniMetric"><span>مؤشر التميز</span><b>${honorPct(p.overall)}</b></div><div class="honorMiniMetric"><span>اختبارات الحصص</span><b>${honorPct(p.test_score)}</b></div><div class="honorMiniMetric"><span>الالتزام</span><b>${honorPct(p.commitment_score)}</b></div><div class="honorMiniMetric"><span>تدريبات المنصة</span><b>${honorPct(p.platform_score)}</b></div></div></div></div>`}
function renderHonorGrade(key){if(!honorData)return;honorGrade=key;const g=honorData.grades?.[key];if(!g)return;document.querySelectorAll('[data-honor-grade]').forEach(b=>b.classList.toggle('active',b.dataset.honorGrade===key));$('honorChallenge').textContent='⚡ '+(g.challenge||'كل نقطة تصنع فرقًا في سباق التميز.');$('honorGradeTitle').textContent='🏆 '+g.label;$('honorEligible').textContent=`${Number(g.stats?.eligible||0)} / ${Number(g.stats?.students||0)}`;$('honorHighest').textContent=honorPct(g.stats?.highest);$('honorRiseStat').textContent=g.stats?.biggest_rise==null?'—':'+'+Number(g.stats.biggest_rise).toFixed(Number(g.stats.biggest_rise)%1?1:0);$('honorLeadingGroup').textContent=g.stats?.leading_group||'—';$('honorGoldCommit').textContent=Number(g.stats?.gold_commitment||0);const p=g.podium||[];$('honorPodium').innerHTML=honorPodiumCard(p[1],2)+honorPodiumCard(p[0],1)+honorPodiumCard(p[2],3);$('honorTop10').innerHTML=honorTopRows(g.top10||[]);$('honorRisers').innerHTML=honorRiserCards(g.risers||[]);$('honorCategories').innerHTML=honorCategories(g);$('honorGroups').innerHTML=honorGroupsView(g.groups||[]);const own=honorData.profile?.grade_key===key;$('honorPersonalWrap').innerHTML=honorPersonalView(g.personal,own);$('honorUpdated').textContent=honorData.generated_at?'آخر تحديث: '+new Date(honorData.generated_at).toLocaleString('ar-EG')+' — تتحدث اللوحة تلقائيًا مع البيانات.':''}
async function openHonorView(){clearMsg();showOnly('honorView');$('honorLoading').innerHTML='<div class="empty">جاري تجهيز لوحة الشرف من البيانات الفعلية...</div>';$('honorLoading').classList.remove('hidden');$('honorContent').classList.add('hidden');try{honorData=await honorFn();const own=honorData.profile?.grade_key||'grade3';renderHonorGrade(own);$('honorLoading').classList.add('hidden');$('honorContent').classList.remove('hidden')}catch(e){$('honorLoading').innerHTML='<div class="msg err">'+esc(e.message||'تعذر تحميل لوحة الشرف')+'</div>'}}
