from pathlib import Path
import re

p=Path('student.html')
s=p.read_text(encoding='utf-8')

# Platform indicator: use weighted actual best scores, not average of percentages.
s=s.replace('إتمام التدريبات ومتوسط أفضل نتيجة معتمدة وأفضل أداء.','إتمام التدريبات وجودة أفضل النتائج الفعلية وأفضل أداء.')
s=s.replace('الإكمال محسوب من التدريبات النشطة، ومتوسط الأداء من أفضل نتيجة معتمدة لكل تدريب.','الإكمال محسوب من التدريبات النشطة، وجودة الأداء = مجموع أفضل الدرجات الفعلية ÷ مجموع نهاياتها.')
s=s.replace('<span class="small muted">متوسط أفضل نتيجة</span>','<span class="small muted">جودة أفضل النتائج</span>')
new_platform=r'''function renderPlatformIndicators(){const activeSlugs=new Set(sets.map(x=>String(x.slug||''))),activeHistory=history.filter(x=>activeSlugs.has(String(x.slug||''))),completed=activeHistory.filter(x=>x.status!=='in_progress'),graded=activeHistory.filter(x=>x.status==='graded'&&x.percentage!=null),completedSets=new Set(completed.map(x=>String(x.slug||x.title||x.id)));$('attemptsStat').textContent=completed.length;$('completedStat').textContent=completedSets.size;const ratio=sets.length?Math.min(100,Math.round(((completedSets.size/sets.length*100)+1e-9)*10)/10):0;$('completionStat').textContent=(Number.isInteger(ratio)?String(ratio):ratio.toFixed(1))+'%';const bestBySet=new Map;graded.forEach(x=>{const k=String(x.slug||x.title||x.id),v=Number(x.percentage),score=Number(x.score),max=Number(x.max_score);if(!Number.isFinite(v))return;const old=bestBySet.get(k);if(!old||v>old.percentage)bestBySet.set(k,{percentage:v,score,max})});const bestValues=[...bestBySet.values()],valid=bestValues.filter(x=>Number.isFinite(x.score)&&Number.isFinite(x.max)&&x.max>0),sumScore=valid.reduce((a,x)=>a+x.score,0),sumMax=valid.reduce((a,x)=>a+x.max,0),quality=sumMax?sumScore/sumMax*100:null,best=bestValues.length?Math.max(...bestValues.map(x=>x.percentage)):null;$('averageStat').textContent=quality==null?'—':(Math.round((quality+1e-9)*10)/10).toFixed(1)+'%';$('bestStat').textContent=best==null?'—':(Math.round((best+1e-9)*10)/10).toFixed(1)+'%'}'''
s,n=re.subn(r'function renderPlatformIndicators\(\)\{.*?\}\nfunction renderSets\(\)',new_platform+'\nfunction renderSets()',s,count=1,flags=re.S)
if n!=1: raise SystemExit('renderPlatformIndicators patch failed')

# Assessment: backend is the source of truth.
new_calc=r'''function assessmentReadinessCalc(d){
  const p=d.pre_comprehensive||{},c=d.cycle||{},w=c.weights||{},num=v=>v==null?null:Number(v);
  return{score:num(p.readiness_score),platformScore:num(p.platform?.score),attendance:num(p.attendance?.rate),homework:num(p.homework?.rate),quizzes:num(p.quizzes?.score_ratio),completion:num(p.platform?.completion_rate)??0,quality:num(p.platform?.quality_ratio),qW:num(w.quizzes)??40,plW:num(w.platform)??30,hW:num(w.homework)??20,aW:num(w.attendance)??10,qualityW:num(w.platform_quality)??60,completionW:num(w.platform_completion)??40};
}'''
s,n=re.subn(r'function assessmentReadinessCalc\(d\)\{.*?\n\}\nfunction renderAssessmentReadiness',new_calc+'\nfunction renderAssessmentReadiness',s,count=1,flags=re.S)
if n!=1: raise SystemExit('assessmentReadinessCalc patch failed')
s=s.replace("comp.status==='absent'?'غائب':'لم تُدخل درجة الشامل بعد'","comp.status==='absent'?'0 / '+Number(comp.max_score)+' (غياب)':'لم تُدخل درجة الشامل بعد'")
s=s.replace('• الكويزات: مجموع الدرجات الفعلية / مجموع نهايات الاختبارات التي لها درجة.<br>• غياب الكويز يظهر منفصلًا ولا يتحول تلقائيًا إلى صفر أكاديمي.<br>• الأوزان النهائية لمؤشر الاستعداد لم تعتمد بعد.','• الكويزات: مجموع الدرجات الفعلية ÷ مجموع نهايات الكويزات المسجلة.<br>• غياب أي كويز أو امتحان يُحسب صفرًا ويدخل بكامل نهاية الاختبار في الحصيلة.<br>• مؤشر الاستعداد: 40% كويزات + 30% منصة + 20% واجب + 10% حضور.')

# Class tests: absence is explicitly 0 everywhere.
s=s.replace("r.status==='absent'?'غائب عن الاختبار':'الدرجة غير مسجلة'","r.status==='absent'?`غياب · 0 / ${Number(r.max_score)} · 0%`:'الدرجة غير مسجلة'")
s=s.replace("<div>${r.status==='scored'?esc(Number(r.score)+' / '+Number(r.max_score)):'—'}</div><div>${r.status==='scored'?pctText(r.percentage):'—'}</div>","<div>${r.status==='scored'||r.status==='absent'?esc(Number(r.score||0)+' / '+Number(r.max_score)):'—'}</div><div>${r.status==='scored'||r.status==='absent'?pctText(r.percentage??0):'—'}</div>")
s=s.replace("$('testsFootnote').textContent='الحصيلة الأكاديمية = مجموع درجات الاختبارات المسجلة ÷ مجموع نهاياتها. لا نأخذ متوسط النسب المنفصلة، والغياب يظهر مستقلًا ولا يتحول تلقائيًا إلى صفر.'","$('testsFootnote').textContent='الحصيلة الأكاديمية = مجموع الدرجات الفعلية ÷ مجموع نهايات الاختبارات المسجلة. غياب أي كويز أو امتحان = صفر ويدخل بكامل نهاية الاختبار في الحصيلة، ولا نأخذ متوسط النسب المنفصلة.'")

# Honor board static copy.
s=s.replace('<h2>🏆 بطولة التميز</h2>','<h2 id="honorArenaTitle">🎯 سباق الاستعداد قبل الشامل</h2>')
s=s.replace('<p class="honorHeroLead">التفوق هنا لا يعني الدرجة فقط؛ الاختبارات والالتزام والواجب والتدريب المستمر كلها تصنع مركزك في السباق.</p>','<p id="honorArenaLead" class="honorHeroLead">هذا ترتيب مبدئي للاستعداد. بعد اكتمال الشامل تتحول الجولة إلى 80% شامل + 20% استعداد.</p>')
s=s.replace('<div class="honorFormula"><span><b>50%</b> اختبارات الحصص</span><span><b>17%</b> الالتزام</span><span><b>17%</b> الواجب</span><span><b>16%</b> تدريبات المنصة</span></div>','<div id="honorFormula" class="honorFormula"><span><b>40%</b> كويزات</span><span><b>30%</b> منصة</span><span><b>20%</b> واجب</span><span><b>10%</b> حضور</span></div>')
s=s.replace('<span>أكبر صعود</span><b id="honorRiseStat">—</b>','<span>استعداد مكتمل</span><b id="honorRiseStat">—</b>')
s=s.replace('<span>التزام ذهبي ≥95%</span><b id="honorGoldCommit">—</b>','<span>درجات شامل مدخلة</span><b id="honorGoldCommit">—</b>')
s=s.replace('<span>أعلى مؤشر تميز</span><b id="honorHighest">—</b>','<span id="honorHighestLabel">أعلى مؤشر استعداد</span><b id="honorHighest">—</b>')
s=s.replace('<h3>📈 نجوم الصعود</h3><p>أكبر تحسن بين آخر اختبارين مسجلين.</p>','<h3 id="honorRiserTitle">📈 نجوم الصعود</h3><p id="honorRiserDesc">أكبر تحسن بين آخر كويزين مسجلين، والغياب يُحسب صفرًا.</p>')
s=s.replace('<p>أفضل 3 في مؤشر التميز العام.</p>','<p>أفضل 3 في الترتيب الحالي مع مراعاة التعادل الحقيقي.</p>')
s=s.replace('<p>تفاصيل مكونات مؤشر التميز لكل متصدر.</p>','<p>الشامل والاستعداد والكويزات والمنصة لكل متصدر.</p>')

new_honor=r'''function honorPodiumCard(s,slotRank,label){if(!s)return '<div></div>';const actualRank=Number(s.rank||slotRank),visualRank=actualRank===1?1:actualRank===2?2:3,medal=actualRank===1?'🥇':actualRank===2?'🥈':'🥉';return `<div class="podiumCard rank${visualRank}"><div class="podiumMedal">${medal}</div><div class="podiumAvatar podiumSymbol" aria-hidden="true">${honorPodiumSymbol(actualRank)}</div><div class="podiumName">${esc(s.full_name)}</div><div class="podiumGroup">${esc(s.group_code||'')}</div><div class="podiumScore"><strong>${honorPct(s.overall)}</strong><span>${esc(label)}</span></div><div class="podiumBadges">${honorBadges(s.badges)}</div></div>`}
function honorMetricCell(label,value){return `<div class="honorCellMetric"><b>${honorPct(value)}</b><span>${label}</span></div>`}
function honorPhaseMeta(p){if(p==='final')return{label:'النتيجة النهائية',title:'🏆 بطولة الجولة — النهائية',lead:'اكتملت بيانات الجولة. الترتيب النهائي = 80% الشامل + 20% مؤشر الاستعداد.',score:'النتيجة النهائية'};if(p==='comprehensive_entry')return{label:'مؤشر الاستعداد',title:'⏳ درجات الشامل قيد الإدخال',lead:'لن نخلط ترتيبًا جزئيًا؛ يظل الظاهر ترتيب الاستعداد حتى تكتمل درجات الشامل لكل الطلاب.',score:'مؤشر الاستعداد'};if(p==='finalizing')return{label:'مؤشر الاستعداد',title:'⏳ الترتيب النهائي قيد التجهيز',lead:'درجات الشامل مكتملة، لكن توجد بيانات استعداد معلقة قبل إعلان الترتيب النهائي.',score:'مؤشر الاستعداد'};return{label:'مؤشر الاستعداد',title:'🎯 سباق الاستعداد قبل الشامل',lead:'ترتيب مبدئي للاستعداد فقط. بعد اكتمال الجولة يصبح 80% شامل + 20% استعداد.',score:'مؤشر الاستعداد'}}
function honorFormulaHtml(p){return p==='final'?'<span><b>80%</b> الشامل</span><span><b>20%</b> الاستعداد</span><span>الاستعداد: <b>40</b> كويزات · <b>30</b> منصة · <b>20</b> واجب · <b>10</b> حضور</span>':'<span><b>40%</b> كويزات</span><span><b>30%</b> منصة</span><span><b>20%</b> واجب</span><span><b>10%</b> حضور</span>'}
function honorTopRows(rows,phase){if(!(rows||[]).length)return '<div class="honorEmpty">لا توجد بيانات مكتملة كافية للترتيب حتى الآن.</div>';const final=phase==='final';return `<div class="honorTopRow honorTopHead"><div>المركز</div><div>الطالب</div><div>${final?'النهائي':'الاستعداد'}</div><div>الشامل</div><div>الاستعداد</div><div>كويزات</div><div>منصة</div></div>`+rows.map(s=>`<div class="honorTopRow"><div><div class="honorRankNum">${s.rank}</div></div><div><div class="honorStudentName">${esc(s.full_name)}</div><div class="honorStudentMeta">${esc(s.group_code||'')} · ${honorBadges(s.badges)}</div></div><div class="honorOverallCell"><b>${honorPct(s.overall)}</b><div class="honorOverallBar"><i style="width:${Math.max(0,Math.min(100,Number(s.overall||0)))}%"></i></div></div>${honorMetricCell('الشامل',s.comprehensive_score)}${honorMetricCell('الاستعداد',s.readiness_score)}${honorMetricCell('كويزات',s.quiz_score)}${honorMetricCell('منصة',s.platform_score)}</div>`).join('')}
function honorRiserCards(rows,phase){if(!(rows||[]).length)return '<div class="honorEmpty" style="grid-column:1/-1">لا توجد بيانات كافية لهذه الفئة بعد.</div>';return rows.map(s=>`<div class="honorRiser"><div class="arrow">↗️</div><div class="rise">+${Number(s.improvement).toFixed(Number(s.improvement)%1?1:0)}</div><div class="nm">${esc(s.full_name)}</div><span class="meta">${esc(s.group_code||'')} · ${phase==='final'?'الشامل أعلى من الاستعداد':honorPct(s.previous_test)+' ← '+honorPct(s.latest_test)}</span></div>`).join('')}
function honorLeaderRows(rows,field){if(!(rows||[]).length)return '<div class="honorEmpty">لا توجد بيانات بعد.</div>';return rows.map((s,i)=>`<div class="honorLeaderRow"><div class="honorLeaderNo">${i+1}</div><div><div class="honorLeaderName">${esc(s.full_name)}</div><div class="honorLeaderGroup">${esc(s.group_code||'')}</div></div><div class="honorLeaderValue">${honorPct(s[field])}</div></div>`).join('')}
function honorCategories(g){const c=[['🧠','أبطال الشامل','comprehensive','comprehensive_score'],['🎯','أبطال الاستعداد','readiness','readiness_score'],['🧪','فرسان الكويزات','quizzes','quiz_score'],['🚀','نجوم المنصة','platform','platform_score'],['📚','أبطال الواجب','homework','homework_score'],['📅','أبطال الحضور','attendance','attendance_rate']];return c.map(([icon,title,key,field])=>`<div class="honorCategory"><div class="honorCategoryTitle"><div class="honorCategoryIcon">${icon}</div><h4>${title}</h4></div>${honorLeaderRows(g.leaders?.[key]||[],field)}</div>`).join('')}
function honorGroupCard(g,i,label){if(!g)return '';return `<div class="honorGroupCard ${i===0?'leading':''}">${i===0?'<div>👑</div>':''}<div class="honorGroupCode">${esc(g.group_code||'')}</div><div class="honorGroupAvg">${honorPct(g.average)} <small>متوسط ${esc(label)}</small></div><div class="small muted">${Number(g.eligible_count||0)} مؤهل من ${Number(g.total_count||0)} طالب</div>${g.leader?`<div class="small" style="margin-top:8px">متصدر المجموعة: <b>${esc(g.leader.full_name)}</b> · ${honorPct(g.leader.overall)}</div>`:''}</div>`}
function honorGroupsView(groups,label){const a=groups?.[0],b=groups?.[1];if(!a)return '<div class="honorEmpty" style="grid-column:1/-1">لا توجد بيانات مجموعات كافية.</div>';if(!b)return honorGroupCard(a,0,label);return `${honorGroupCard(a,0,label)}<div class="honorVs">VS</div>${honorGroupCard(b,1,label)}`}
function honorPersonalView(p,ownGrade,phase){if(!ownGrade)return '<div class="honorPersonal"><div class="honorRankOrb"><div><b>↔</b><span>صف آخر</span></div></div><div><h3>أنت تشاهد منافسة الصف الآخر</h3><p>يمكنك استكشاف اللوحة، لكن مركزك الشخصي يظهر فقط داخل صفك الدراسي.</p></div></div>';if(!p)return '';if(!p.eligible)return `<div class="honorPersonal"><div class="honorRankOrb"><div><b>—</b><span>مركزك</span></div></div><div><h3>مكانك في السباق</h3><p>${esc(p.message||'بانتظار اكتمال البيانات.')}</p><div class="honorPersonalMetrics"><div class="honorMiniMetric"><span>البيانات الناقصة</span><b>${esc((p.missing||[]).join(' + ')||'—')}</b></div><div class="honorMiniMetric"><span>الكويزات</span><b>${honorPct(p.quiz_score)}</b></div><div class="honorMiniMetric"><span>المنصة</span><b>${honorPct(p.platform_score)}</b></div></div></div></div>`;return `<div class="honorPersonal"><div class="honorRankOrb"><div><b>#${p.rank}</b><span>من ${p.total_eligible}</span></div></div><div><h3>🔥 مكانك في السباق</h3><p>${esc(p.message||'')}</p><div class="podiumBadges" style="justify-content:flex-start">${honorBadges(p.badges)}</div><div class="honorPersonalMetrics"><div class="honorMiniMetric"><span>${phase==='final'?'النتيجة النهائية':'مؤشر الاستعداد'}</span><b>${honorPct(p.overall)}</b></div><div class="honorMiniMetric"><span>الشامل</span><b>${honorPct(p.comprehensive_score)}</b></div><div class="honorMiniMetric"><span>الاستعداد</span><b>${honorPct(p.readiness_score)}</b></div><div class="honorMiniMetric"><span>المنصة</span><b>${honorPct(p.platform_score)}</b></div></div></div></div>`}
function renderHonorGrade(key){if(!honorData)return;honorGrade=key;const g=honorData.grades?.[key];if(!g)return;const pm=honorPhaseMeta(g.phase);document.querySelectorAll('[data-honor-grade]').forEach(b=>b.classList.toggle('active',b.dataset.honorGrade===key));$('honorArenaTitle').textContent=pm.title;$('honorArenaLead').textContent=pm.lead;$('honorFormula').innerHTML=honorFormulaHtml(g.phase);$('honorChallenge').textContent='⚡ '+(g.challenge||'');$('honorGradeTitle').textContent='🏆 '+g.label;$('honorEligible').textContent=`${Number(g.stats?.eligible||0)} / ${Number(g.stats?.students||0)}`;$('honorHighestLabel').textContent='أعلى '+pm.score;$('honorHighest').textContent=honorPct(g.stats?.highest);$('honorRiseStat').textContent=`${Number(g.stats?.readiness_ready||0)} / ${Number(g.stats?.participants||0)}`;$('honorLeadingGroup').textContent=g.stats?.leading_group||'—';$('honorGoldCommit').textContent=`${Number(g.stats?.comprehensive_recorded||0)} / ${Number(g.stats?.comprehensive_expected||0)}`;const p=g.podium||[];$('honorPodium').innerHTML=honorPodiumCard(p[1],2,pm.score)+honorPodiumCard(p[0],1,pm.score)+honorPodiumCard(p[2],3,pm.score);$('honorTop10').innerHTML=honorTopRows(g.top10||[],g.phase);$('honorRiserTitle').textContent=g.phase==='final'?'📈 تجاوز التوقع':'📈 نجوم الصعود';$('honorRiserDesc').textContent=g.phase==='final'?'طلاب جاءت نتيجة الشامل لديهم أعلى من مؤشر الاستعداد.':'أكبر تحسن بين آخر كويزين مسجلين، والغياب يُحسب صفرًا.';$('honorRisers').innerHTML=honorRiserCards(g.risers||[],g.phase);$('honorCategories').innerHTML=honorCategories(g);$('honorGroups').innerHTML=honorGroupsView(g.groups||[],pm.score);const own=honorData.profile?.grade_key===key;$('honorPersonalWrap').innerHTML=honorPersonalView(g.personal,own,g.phase);$('honorUpdated').textContent=honorData.generated_at?'آخر تحديث: '+new Date(honorData.generated_at).toLocaleString('ar-EG')+' — كل الحسابات من محرك دورة التقييم الموحد.':''}
async function openHonorView(){clearMsg();showOnly('honorView');$('honorLoading').innerHTML='<div class="empty">جاري تجهيز لوحة الشرف من محرك التقييم الموحد...</div>';$('honorLoading').classList.remove('hidden');$('honorContent').classList.add('hidden');try{honorData=await honorFn();const own=honorData.profile?.grade_key||'grade3';renderHonorGrade(own);$('honorLoading').classList.add('hidden');$('honorContent').classList.remove('hidden')}catch(e){$('honorLoading').innerHTML='<div class="msg err">'+esc(e.message||'تعذر تحميل لوحة الشرف')+'</div>'}}'''
s,n=re.subn(r'function honorPodiumCard\(.*?\nasync function openHonorView\(\)\{.*?\}\n\nfunction pctText',new_honor+'\n\nfunction pctText',s,count=1,flags=re.S)
if n!=1: raise SystemExit('honor functions patch failed')

p.write_text(s,encoding='utf-8')

# Admin assessment: render the readiness returned by the central engine, don't recalculate client-side.
p=Path('assessment-admin.html')
a=p.read_text(encoding='utf-8')
a=a.replace('const ready=adminReadiness(r,c);return','const ready=r.readiness_score==null?null:Number(r.readiness_score);return')
a=a.replace('الكويزات تعرض الدرجات الفعلية، وتدريبات المنصة تتوقف عند وقت تسليم الطالب قبل الـCutoff.','الكويزات تعرض حصيلة الدرجات الفعلية، والغياب يُحسب صفرًا. تدريبات المنصة تتوقف عند وقت تسليم الطالب قبل الـCutoff.')
p.write_text(a,encoding='utf-8')
