from pathlib import Path

p = Path('student.html')
s = p.read_text(encoding='utf-8')

css = r'''
.studentHomeGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-top:16px}.studentNavCard{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;min-height:210px;text-decoration:none;color:inherit;cursor:pointer;transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease;position:relative}.studentNavCard:hover{transform:translateY(-3px);border-color:#b8c5e0;box-shadow:0 12px 28px rgba(15,23,42,.09)}.studentNavIcon{width:78px;height:78px;border-radius:24px;display:grid;place-items:center;font-size:38px;background:#eef2ff;margin-bottom:15px}.studentNavCard h3{margin:0 0 7px;font-size:21px}.studentNavCard p{margin:0;color:#667085;font-size:13px;line-height:1.7;max-width:260px}.studentSubGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.studentSubGrid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.studentSubHead{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px}.studentSubHead h2{margin:0;font-size:22px}.studentBack{white-space:nowrap}.profilePills{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.profilePills span{background:rgba(255,255,255,.13);border:1px solid rgba(255,255,255,.16);border-radius:999px;padding:6px 10px;font-size:12px}.soonBadge{position:absolute;top:14px;left:14px;background:#fff7ed;color:#c2410c;border:1px solid #fed7aa;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:900}.soonBox{text-align:center;padding:42px 20px}.soonIcon{font-size:54px;margin-bottom:10px}.metricGrid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.metricGrid .stat{text-align:center}.metricGrid .stat b{font-size:26px}.sectionIntro{color:#667085;margin:5px 0 0;font-size:13px;line-height:1.7}
html[data-theme="dark"] .studentNavIcon{background:#1e293b}html[data-theme="dark"] .studentNavCard p,html[data-theme="dark"] .sectionIntro{color:#9ca3af}html[data-theme="dark"] .soonBadge{background:#431407;color:#fdba74;border-color:#7c2d12}
@media(max-width:760px){.studentHomeGrid,.studentSubGrid,.studentSubGrid.two{grid-template-columns:1fr}.studentNavCard{min-height:165px}.studentSubHead{align-items:flex-start;flex-direction:column}.metricGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.metricGrid .stat:last-child{grid-column:span 2}}
'''
if '</style>' not in s:
    raise SystemExit('style end marker missing')
s = s.replace('</style>', css + '\n</style>', 1)

old_dashboard = '''<section id="dashboardView" class="hidden">
<div class="hero card"><h2 id="welcomeTitle">أهلاً بك</h2><p>اختر تدريبًا وابدأ الحل. نتائجك ومحاولاتك محفوظة تلقائيًا.</p></div>
<div class="grid"><div class="c8 card"><h2 style="margin-top:0;font-size:19px">التدريبات المتاحة</h2><div id="setsList"></div></div><div class="c4"><div class="card"><h3 style="margin-top:0">ملخصك</h3><div class="grid"><div class="c6 stat"><b id="attemptsStat">0</b><span class="small muted">محاولة</span></div><div class="c6 stat"><b id="bestStat">—</b><span class="small muted">أفضل نتيجة</span></div></div></div></div></div>
<div class="card"><h2 style="margin-top:0;font-size:19px">سجل المحاولات</h2><div id="historyList"></div></div>
</section>'''
new_dashboard = '''<section id="dashboardView" class="hidden">
<div class="hero card"><h2 id="welcomeTitle">أهلاً بك</h2><p>كل ما يخص تدريباتك ومؤشراتك في مكان واحد.</p><div id="studentProfileMeta" class="profilePills"></div></div>
<div class="studentHomeGrid">
<button id="openTrainings" class="card studentNavCard" type="button"><div class="studentNavIcon">📝</div><h3>التدريبات</h3><p>التدريبات المتاحة وما أنجزته من تدريبات المنصة.</p></button>
<button id="openIndicators" class="card studentNavCard" type="button"><div class="studentNavIcon">📊</div><h3>مؤشراتي</h3><p>متابعة مؤشرات الالتزام والاختبارات وتدريبات المنصة.</p></button>
<button id="openHonor" class="card studentNavCard" type="button"><div class="studentNavIcon">🏆</div><h3>لوحة الشرف</h3><p>لوحة الشرف الديناميكية لطلاب الفيزياء.</p><span class="soonBadge">قريبًا</span></button>
</div>
</section>
<section id="trainingMenuView" class="hidden"><div class="studentSubHead"><div><h2>📝 التدريبات</h2><p class="sectionIntro">اختر ما تريد عرضه.</p></div><button class="btn secondary studentBack" data-go-home>العودة للرئيسية</button></div><div class="studentSubGrid two"><button id="openAvailable" class="card studentNavCard" type="button"><div class="studentNavIcon">🚀</div><h3>التدريبات المتاحة</h3><p>ابدأ تدريبًا جديدًا من التدريبات المتاحة لك.</p></button><button id="openCompleted" class="card studentNavCard" type="button"><div class="studentNavIcon">✅</div><h3>التدريبات المكتملة</h3><p>راجع محاولاتك السابقة ونتائجك وتصحيحها.</p></button></div></section>
<section id="indicatorsMenuView" class="hidden"><div class="studentSubHead"><div><h2>📊 مؤشراتي</h2><p class="sectionIntro">مؤشراتك التعليمية في مكان واحد.</p></div><button class="btn secondary studentBack" data-go-home>العودة للرئيسية</button></div><div class="studentSubGrid"><button id="openCommitment" class="card studentNavCard" type="button"><div class="studentNavIcon">🎯</div><h3>مؤشر الالتزام</h3><p>الحضور والواجب والالتزام بالحصة.</p><span class="soonBadge">قريبًا</span></button><button id="openClassTests" class="card studentNavCard" type="button"><div class="studentNavIcon">🧪</div><h3>اختبارات الحصص</h3><p>متوسط ونتائج الكويزات والاختبارات الشاملة.</p><span class="soonBadge">قريبًا</span></button><button id="openPlatformIndicators" class="card studentNavCard" type="button"><div class="studentNavIcon">📈</div><h3>تدريبات المنصة</h3><p>إتمام التدريبات ومتوسط الدرجات وأفضل نتيجة.</p></button></div></section>
<section id="availableTrainingsView" class="hidden"><div class="studentSubHead"><div><h2>🚀 التدريبات المتاحة</h2><p class="sectionIntro">اختر التدريب وابدأ الحل.</p></div><button id="backTrainingMenu1" class="btn secondary studentBack">العودة للتدريبات</button></div><div class="card"><div id="setsList"></div></div></section>
<section id="completedTrainingsView" class="hidden"><div class="studentSubHead"><div><h2>✅ التدريبات المكتملة</h2><p class="sectionIntro">محاولاتك التي تم تسليمها ونتائجها.</p></div><button id="backTrainingMenu2" class="btn secondary studentBack">العودة للتدريبات</button></div><div class="card"><div id="historyList"></div></div></section>
<section id="platformIndicatorsView" class="hidden"><div class="studentSubHead"><div><h2>📈 مؤشر تدريبات المنصة</h2><p class="sectionIntro">المؤشرات محسوبة من تدريباتك ومحاولاتك الحالية على المنصة.</p></div><button id="backIndicatorsMenu" class="btn secondary studentBack">العودة لمؤشراتي</button></div><div class="card"><div class="metricGrid"><div class="stat"><b id="completedStat">0</b><span class="small muted">تدريب مكتمل</span></div><div class="stat"><b id="completionStat">0%</b><span class="small muted">نسبة الإكمال</span></div><div class="stat"><b id="attemptsStat">0</b><span class="small muted">محاولة مكتملة</span></div><div class="stat"><b id="averageStat">—</b><span class="small muted">متوسط الدرجات</span></div><div class="stat"><b id="bestStat">—</b><span class="small muted">أفضل نتيجة</span></div></div></div></section>
<section id="comingSoonView" class="hidden"><div class="studentSubHead"><div><h2 id="soonTitle">قريبًا</h2></div><button id="soonBackBtn" class="btn secondary studentBack">العودة</button></div><div class="card soonBox"><div class="soonIcon">🚧</div><h2 style="margin:0 0 8px">قريبًا</h2><p id="soonText" class="muted" style="margin:0;line-height:1.8"></p></div></section>'''
if old_dashboard not in s:
    raise SystemExit('dashboard block target missing')
s = s.replace(old_dashboard, new_dashboard, 1)

old_show = "function emailForCode(c){return c.trim().toLowerCase().replace(/\\s+/g,'')+'@students.yrphysicspractice.com'}function showMsg(t,type='err'){$('msg').innerHTML='<div class=\"msg '+type+'\">'+esc(t)+'</div>'}function clearMsg(){$('msg').innerHTML=''}function showOnly(id){['loginView','dashboardView','practiceView','resultView','reviewView'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}"
new_show = "function emailForCode(c){return c.trim().toLowerCase().replace(/\\s+/g,'')+'@students.yrphysicspractice.com'}function showMsg(t,type='err'){$('msg').innerHTML='<div class=\"msg '+type+'\">'+esc(t)+'</div>'}function clearMsg(){$('msg').innerHTML=''}const STUDENT_VIEWS=['loginView','dashboardView','trainingMenuView','indicatorsMenuView','availableTrainingsView','completedTrainingsView','platformIndicatorsView','comingSoonView','practiceView','resultView','reviewView'];function showOnly(id){STUDENT_VIEWS.forEach(x=>$(x).classList.toggle('hidden',x!==id));window.scrollTo({top:0,behavior:'smooth'})}"
if old_show not in s:
    raise SystemExit('showOnly target missing')
s = s.replace(old_show, new_show, 1)

old_init = "async function initSession(){const d=await fn({action:'ping'});profile=d.profile;$('studentName').textContent=(profile.full_name||'طالب')+' — '+(profile.student_code||'');$('welcomeTitle').textContent='أهلاً '+(profile.full_name||'');$('loginView').classList.add('hidden');$('userBar').classList.remove('hidden');await loadDashboard();showOnly('dashboardView')}"
new_init = "function gradeLabel(v){const x=String(v||'').toLowerCase();if(x==='2'||x==='2_secondary'||x.includes('second'))return'الصف الثاني الثانوي';if(x==='3'||x==='3_secondary'||x.includes('third'))return'الصف الثالث الثانوي';return v||''}function renderProfileMeta(){const vals=[profile?.student_code,gradeLabel(profile?.grade_level),profile?.group_code,profile?.center_name].filter(Boolean);$('studentProfileMeta').innerHTML=vals.map(v=>'<span>'+esc(v)+'</span>').join('')}async function initSession(){const d=await fn({action:'ping'});profile=d.profile;$('studentName').textContent=(profile.full_name||'طالب')+' — '+(profile.student_code||'');$('welcomeTitle').textContent='أهلاً '+(profile.full_name||'')+' 👋';renderProfileMeta();$('loginView').classList.add('hidden');$('userBar').classList.remove('hidden');await loadDashboard();showOnly('dashboardView')}"
if old_init not in s:
    raise SystemExit('initSession target missing')
s = s.replace(old_init, new_init, 1)

old_load = "async function loadDashboard(){const[a,b]=await Promise.all([fn({action:'list_sets'}),fn({action:'history'})]);sets=a.sets||[];history=b.attempts||[];renderSets();renderHistory();$('attemptsStat').textContent=history.length;const graded=history.filter(x=>x.percentage!=null);$('bestStat').textContent=graded.length?Math.max(...graded.map(x=>Number(x.percentage)))+'%':'—'}"
new_load = "async function loadDashboard(){const[a,b]=await Promise.all([fn({action:'list_sets'}),fn({action:'history'})]);sets=a.sets||[];history=b.attempts||[];renderSets();renderHistory();renderPlatformIndicators()}function renderPlatformIndicators(){const completed=history.filter(x=>x.status!=='in_progress'),graded=completed.filter(x=>x.percentage!=null),unique=new Set(completed.map(x=>String(x.training_set_id||x.title||x.id)));$('attemptsStat').textContent=completed.length;$('completedStat').textContent=unique.size;const ratio=sets.length?Math.min(100,Math.round(unique.size/sets.length*100)):0;$('completionStat').textContent=ratio+'%';$('averageStat').textContent=graded.length?(graded.reduce((a,x)=>a+Number(x.percentage||0),0)/graded.length).toFixed(1)+'%':'—';$('bestStat').textContent=graded.length?Math.max(...graded.map(x=>Number(x.percentage)))+'%':'—'}"
if old_load not in s:
    raise SystemExit('loadDashboard target missing')
s = s.replace(old_load, new_load, 1)

old_history = "function renderHistory(){if(!history.length){$('historyList').innerHTML='<div class=\"empty\">لا توجد محاولات بعد.</div>';return}$('historyList').innerHTML=history.map(h=>'<div class=\"historyRow\"><div><b>'+esc(h.title)+'</b><div class=\"small muted\">'+new Date(h.started_at).toLocaleString('ar-EG')+'</div>'+(h.status!=='in_progress'?'<button class=\"btn secondary historyReviewBtn\" data-review-attempt=\"'+esc(h.id)+'\">عرض التصحيح</button>':'')+'</div><div><span class=\"pill\">'+esc(historyStatusLabel(h.status))+'</span></div><div><b>'+(h.percentage==null?'—':Number(h.percentage)+'%')+'</b><div class=\"small muted\">'+(h.score==null?'':Number(h.score)+' / '+Number(h.max_score))+'</div></div></div>').join('');document.querySelectorAll('[data-review-attempt]').forEach(b=>b.onclick=()=>openAttemptReview(b.dataset.reviewAttempt))}"
new_history = "function renderHistory(){const completed=history.filter(h=>h.status!=='in_progress');if(!completed.length){$('historyList').innerHTML='<div class=\"empty\">لم تكمل أي تدريب بعد.</div>';return}$('historyList').innerHTML=completed.map(h=>'<div class=\"historyRow\"><div><b>'+esc(h.title)+'</b><div class=\"small muted\">'+new Date(h.started_at).toLocaleString('ar-EG')+'</div><button class=\"btn secondary historyReviewBtn\" data-review-attempt=\"'+esc(h.id)+'\">عرض التصحيح</button></div><div><span class=\"pill\">'+esc(historyStatusLabel(h.status))+'</span></div><div><b>'+(h.percentage==null?'—':Number(h.percentage)+'%')+'</b><div class=\"small muted\">'+(h.score==null?'':Number(h.score)+' / '+Number(h.max_score))+'</div></div></div>').join('');document.querySelectorAll('[data-review-attempt]').forEach(b=>b.onclick=()=>openAttemptReview(b.dataset.reviewAttempt))}"
if old_history not in s:
    raise SystemExit('renderHistory target missing')
s = s.replace(old_history, new_history, 1)

old_back_review = "$('backReviewBtn').onclick=()=>showOnly('dashboardView');"
new_nav = """let soonReturnView='dashboardView';function openSoon(title,text,back='dashboardView'){$('soonTitle').textContent=title;$('soonText').textContent=text;soonReturnView=back;showOnly('comingSoonView')}$('openTrainings').onclick=()=>showOnly('trainingMenuView');$('openIndicators').onclick=()=>showOnly('indicatorsMenuView');$('openHonor').onclick=()=>openSoon('🏆 لوحة الشرف','نعمل حاليًا على تجهيز لوحة شرف ديناميكية تعتمد على بيانات الحصص والتدريبات.','dashboardView');document.querySelectorAll('[data-go-home]').forEach(b=>b.onclick=()=>showOnly('dashboardView'));$('openAvailable').onclick=()=>showOnly('availableTrainingsView');$('openCompleted').onclick=()=>showOnly('completedTrainingsView');$('backTrainingMenu1').onclick=()=>showOnly('trainingMenuView');$('backTrainingMenu2').onclick=()=>showOnly('trainingMenuView');$('openPlatformIndicators').onclick=()=>showOnly('platformIndicatorsView');$('backIndicatorsMenu').onclick=()=>showOnly('indicatorsMenuView');$('openCommitment').onclick=()=>openSoon('🎯 مؤشر الالتزام','قريبًا — سيتم تفعيل المؤشر بعد ربط بيانات الحضور والواجب المسجلة في الحصص بصفحة الطالب.','indicatorsMenuView');$('openClassTests').onclick=()=>openSoon('🧪 اختبارات الحصص','قريبًا — سيتم عرض نتائج الكويزات والاختبارات الشاملة بعد ربط بيانات الحصص بصفحة الطالب.','indicatorsMenuView');$('soonBackBtn').onclick=()=>showOnly(soonReturnView);$('backReviewBtn').onclick=()=>showOnly('completedTrainingsView');"""
if old_back_review not in s:
    raise SystemExit('backReview target missing')
s = s.replace(old_back_review, new_nav, 1)

old_back_result = "$('backDashboardBtn').onclick=async()=>{attemptId=null;currentSet=null;questions=[];answers={};$('finishBtn').disabled=false;await loadDashboard();showOnly('dashboardView')};"
new_back_result = "$('backDashboardBtn').onclick=async()=>{attemptId=null;currentSet=null;questions=[];answers={};$('finishBtn').disabled=false;await loadDashboard();showOnly('availableTrainingsView')};"
if old_back_result not in s:
    raise SystemExit('back result target missing')
s = s.replace(old_back_result, new_back_result, 1)

p.write_text(s, encoding='utf-8')
print('student dashboard patch applied')
