create schema if not exists private;

create table if not exists public.l6_workshop_questions (
  bank_no integer primary key,
  question_id text not null unique,
  skill text not null,
  skill_name text not null,
  subskill text not null,
  subskill_name text not null,
  track text not null check (track in ('class','home')),
  sort_order integer not null check (sort_order > 0),
  difficulty text not null,
  question_profile text not null,
  image_path text not null,
  image_width integer,
  image_height integer,
  image_sha256 text not null,
  parts_schema jsonb not null default '[]'::jsonb check (jsonb_typeof(parts_schema)='array' and jsonb_array_length(parts_schema)>=1),
  active boolean not null default true,
  diagnostic_tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists l6_workshop_questions_track_order_uq on public.l6_workshop_questions(track,sort_order);
create index if not exists l6_workshop_questions_track_order_idx on public.l6_workshop_questions(track,sort_order,bank_no);
create index if not exists l6_workshop_questions_skill_idx on public.l6_workshop_questions(skill,subskill);
alter table public.l6_workshop_questions enable row level security;

create table if not exists private.l6_workshop_keys (
  bank_no integer not null references public.l6_workshop_questions(bank_no) on delete cascade,
  part_key text not null,
  grading_mode text not null check (grading_mode in ('mcq_letter','qualitative_choice','numeric','ratio','symbolic','structured_text')),
  answer_spec jsonb not null,
  display_answer text not null,
  verified boolean not null default true,
  solution_note text,
  updated_at timestamptz not null default now(),
  primary key(bank_no,part_key)
);
alter table private.l6_workshop_keys enable row level security;

create table if not exists public.l6_workshop_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  bank_no integer not null references public.l6_workshop_questions(bank_no) on delete cascade,
  part_key text not null,
  attempts_count integer not null default 0 check (attempts_count>=0),
  tried_answers jsonb not null default '[]'::jsonb check (jsonb_typeof(tried_answers)='array'),
  first_attempt_correct boolean,
  mastered boolean not null default false,
  revealed boolean not null default false,
  last_answer jsonb check (last_answer is null or jsonb_typeof(last_answer)='object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(user_id,bank_no,part_key),
  constraint l6_workshop_progress_state_exclusive check (not (mastered and revealed))
);
create index if not exists l6_workshop_progress_user_idx on public.l6_workshop_progress(user_id,updated_at desc);
create index if not exists l6_workshop_progress_bank_idx on public.l6_workshop_progress(bank_no,mastered,revealed);
alter table public.l6_workshop_progress enable row level security;

create table if not exists public.l6_workshop_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bank_no integer not null references public.l6_workshop_questions(bank_no) on delete cascade,
  part_key text not null,
  event_type text not null check (event_type in ('attempt','reveal')),
  attempt_no integer,
  answer_json jsonb,
  is_correct boolean,
  created_at timestamptz not null default now(),
  constraint l6_workshop_events_payload_shape check (
    (event_type='attempt' and attempt_no>=1 and answer_json is not null and jsonb_typeof(answer_json)='object' and is_correct is not null)
    or (event_type='reveal' and attempt_no is null and answer_json is null and is_correct is null)
  )
);
create unique index if not exists l6_workshop_events_attempt_unique on public.l6_workshop_events(user_id,bank_no,part_key,attempt_no) where event_type='attempt';
create unique index if not exists l6_workshop_events_reveal_unique on public.l6_workshop_events(user_id,bank_no,part_key) where event_type='reveal';
create index if not exists l6_workshop_events_user_idx on public.l6_workshop_events(user_id,created_at desc);
create index if not exists l6_workshop_events_question_idx on public.l6_workshop_events(bank_no,created_at desc);
alter table public.l6_workshop_events enable row level security;
